chapters:
	cp ../DSLsofMathNotes.pdf .
	pdftk DSLsofMathNotes.pdf cat  9-26 output DSLsofMath_Chapter_1.pdf
	pdftk DSLsofMathNotes.pdf cat 27-46 output DSLsofMath_Chapter_2.pdf
	pdftk DSLsofMathNotes.pdf cat 47-62 output DSLsofMath_Chapter_3.pdf
	pdftk DSLsofMathNotes.pdf cat 63-78 output DSLsofMath_Chapter_4.pdf
	echo "Now rename and check in if the change is big enough for a new snapshot"
