resolver:
  lts-21.25   # uses ghc-9.4.8
#  lts-22.4    # uses ghc-9.6.3

# User packages to be built.
packages:
- '.'


extra-deps:
- github: DSLsofMath/Hatlab
  commit: 8a842849a7f492c430afb2d648d8ff0e95628d35


flags: {}

